version: '3'

# Reference: https://www.jenkins.io/doc/book/installing/docker/
services:
  docker:
    container_name: docker
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    ports:
      - "2376:2376"
    networks:
      - jenkins
    privileged: true

  jenkins:
    container_name: jenkins
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      JENKINS_JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - $PWD/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins: